name: recap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.11
  flutter_dotenv: ^5.1.0
  supabase: ^1.11.11
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  camera: ^0.10.5+5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
